# Generated by Django 4.0.3 on 2022-03-29 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='', max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('Mobile', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Address', models.TextField()),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_app.master')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
