# Generated by Django 4.0.3 on 2022-04-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=10),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=40)),
                ('Description', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Price', models.IntegerField()),
                ('Image', models.FileField(upload_to='images/')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_app.profile')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordered', models.BooleanField(default=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_app.product')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_app.profile')),
            ],
            options={
                'db_table': 'orderitem',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_app.profile')),
                ('items', models.ManyToManyField(to='E_app.orderitem')),
            ],
        ),
    ]
