# Generated by Django 4.0.3 on 2022-04-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0002_alter_profile_gender_product_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Profile',
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptops'), ('Hp', 'Headphones'), ('Kb', 'Keyboards'), ('Mo', 'Mouse')], max_length=4),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_app.product'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_app.profile'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='items',
            field=models.ManyToManyField(to='E_app.orderitem'),
        ),
    ]
