# Generated by Django 4.0.4 on 2022-04-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0003_orderplaced_remove_product_profile_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Cart',
        ),
    ]
