# Generated by Django 4.0.4 on 2022-04-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0004_rename_orderitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Cart',
            old_name='Product',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='Cart',
            name='Ordered',
        ),
    ]
