# Generated by Django 4.0.4 on 2022-04-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0006_rename_product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Cart',
            name='Profile',
        ),
        migrations.AddField(
            model_name='Cart',
            name='Master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='E_app.master'),
            preserve_default=False,
        ),
    ]
