# Generated by Django 4.0.4 on 2022-04-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0007_remove_cart_profile_cart_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Master',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
